# Camera information.
camera_information:
  sensor_height_mm: 9.6      # Camera Sensor height in mm
  sensor_height_px: 960      # Camera feed native pixel resolution height   
  focal_length: 17 
  
# Target Object information
target_object:
  target: person
  real_object_height: 1700     # Target Object physical height in mm
